---
- hosts: gogs
  vars_files:
    - vars/main.yml

  tasks:
  - name: Update all packages
    yum: name=* state=latest
  roles:
    - role: geerlingguy.mysql
      become: yes
    - role: geerlingguy.gogs
      become: yes
    - role: caddy-ansible
      caddy_config: |
        :443 {
          gzip
          tls self_signed
          proxy / localhost:3000 {

          }
        }
        
